name = "Pseudospectrum"
uuid = "5365da1c-89f6-4648-b94d-203e5a11caa7"
authors = ["Miguel Zilhão"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
